### PR TITLE
Support for lazy-loading values with variable expiration

### PR DESCRIPTION
**Pull request by hansenc**
Addresses #17

### CODE REVIEW

**Comment by jhalterman** [comment]
Thanks for this! A few comments: 

* Instead of `IllegalArgumentException` when both loaders are set, it should probably be `IllegalStateException` (since the argument is valid, it just depends on the current state of the builder). I'd also move throwing that exception into the builder's `entryLoader` and `expiringEntryLoader` methods themselves and Javadoc it there with `@throws`
* I think the `ExpiringValue.Builder` might be overkill. The rule of thumb for a builder is any more than 4 constructors and you should consider a builder, so it's close here, but I think just using constructors would be pretty straightforward for users since they would mirror the 4 `ExpiringMap.put` methods (the Javadoc could even reference them).

**Comment by hansenc** [comment]
Good call on `IllegalStateException`. I've made those changes. Regarding `ExpiringValue.Builder` vs. telescoping constructors: if I understand what you are saying, the telescoping constructors for `ExpiringValue` should behave exactly like the 4 `ExpiringMap.put` methods. Meaning it should use the config from the map instance when `expirationPolicy` and/or the (`duration`, `timeUnit`) pair are unspecified. I really like the symmetry of that approach. I'll take a stab at that and see how it turns out.

One style question for you: telescoping constructors or static factory methods? I have a slight preference for static factory methods (e.g. `ExpiringValue.of(V)`, `ExpiringValue.of(V, ExpirationPolicy)`) because they play more nicely with inference of the generic type (pretty much moot in Java 7+), but I don't feel strongly about it in this case. That is, unless we can come up with meaningful method names for the factory methods - nothing jumps out at me.

**Comment by jhalterman** [comment]
> it should use the config from the map instance when expirationPolicy and/or the (duration, timeUnit) pair are unspecified. 

Yep, that's what I was thinking, and just having one constructor to correspond to each `put` method is straightforward. On constructors versus static `of` methods - I like and have used the `of` approach, but for a simple object like this I think constructors are fine. Java 7 is common enough that hopefully people don't mind :)

**Comment by hansenc** [comment]
I ended up using factory methods in order to get around some implementation coupling between `ExpiringMap` and `ExpiringValue`. Have a look at 7e83e94f010b4ec3b3912a969463a208975e2398 and if you don't think it's worth it, I can revert it .

**Comment by jhalterman** [comment]
Hey Chris - 

I actually like it in the first commit - the factory method stuff still just seems overkill. There is coupling, but it's fine here since `ExpiringValue` basically only exists to serve `ExpiringMap` - similar to `Map` and `Map.Entry`. I'd even make ExpiringMap a static internal class if ExpiringMap wasn't getting so large already.

If you don't like the look of `ExpiringMap.putExpiringValue`, an alternative could be something like this:
```
put(key, 
  expiringValue.getValue(),
  expiringValue.getExpirationPolicy() == null ? expirationPolicy.get() : expiringValue.getExpirationPolicy())
  expiringValue.getDuration() == null ? .... etc.
```

**Comment by hansenc** [comment]
Yeah, I didn't like all of the `if/else` branching, so that's a better way to go. I'll make that change.

**Comment by hansenc** [comment]
Should be good to go now.

**Comment by jhalterman** [comment]
Thanks a lot for this!

**Pull request merged**
